### ISSUE TITLE
Spring Data JPA

### ISSUE THREAD

**Issue by kgoralski** [bwajtr/java-persistence-frameworks-comparison#9]
Quote: 
'So we dropped JPA completely, started using JDBCTemplate and discovered that we can deliver apps sooner (which was kind of surprising), they are a lot faster (thanks to effective use of DB) and much more robust... This was really relaxing and we do not plan to return to JPA at all... (yes, even for CRUD applications!)' 

That is fine. I just want to ask one question :) Before you dropped JPA, have you tried JPA... with Spring Data? 
http://projects.spring.io/spring-data-jpa/
http://www.baeldung.com/the-persistence-layer-with-spring-data-jpa
http://docs.spring.io/spring-data/data-jpa/docs/1.1.x/reference/html/#jpa.query-methods.query-creation
or switched before that? ;)

**Comment by bwajtr** [comment]
RE: Have you tried Spring Data JPA?

Yes we did... Spring Data JPA actually only makes some of the querying easier, however there is still full blown JPA in the background - with all the stuff we do want anymore: like Entity Manager, JPQL, relations modelling in java code etc... So Spring Data JPA is just another layer on top of JPA - that's exactly opposite of what I would like to see on repository layer -> be as close to RDBMS as possible...

Thanks for your comment though - I found this project thanks to you and I belive it worth trying: the beauty of Spring Data simple querying, but without full-JPA:  https://github.com/jirutka/spring-data-jdbc-repository
